(compile-file "smtintfuncsynthsygusmultifun.lisp")
(load "smtintfuncsynthsygusmultifun.fasl")

(defun main ()
  (declaim (sb-ext:muffle-conditions cl:warning))
  (if (not (cdr sb-ext:*posix-argv*))
      (format t "Usage: smtintfuncsyntsygusmultifun [-t <mstimelimit>] [-v <num>] [-convert] [-lash <lashexec>] [-cvc5 <cvc5exec>] <smt2file>~%")
    (let ((fn (car (last sb-ext:*posix-argv*))))
      (let ((tm (member "-t" sb-ext:*posix-argv* :test #'equal)))
	(when tm (setq *tlimitms* (read-from-string (cadr tm)))))
      (let ((v (member "-v" sb-ext:*posix-argv* :test #'equal)))
	(when v (setq *verbosity* (read-from-string (cadr v)))))
      (when (member "-convert" sb-ext:*posix-argv* :test #'equal)
	(setq *convert* t))
      (let ((l (member "-lash" sb-ext:*posix-argv* :test #'equal)))
	(when l (setq *lash* (cadr l))))
      (let ((c (member "-cvc5" sb-ext:*posix-argv* :test #'equal)))
	(when c (setq *cvc5* (cadr c))))
      (smtintfuncsynth fn)
      (exit))))

(sb-ext:save-lisp-and-die "smtintfuncsynthsygusmultifun" :save-runtime-options t :executable t :toplevel #'main)
